const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file, extras={}){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(__dirname+'/'+file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{module:m,exports:m.exports,process:{env:{NEXT_PUBLIC_DEV_PWA_DIAGNOSTICS:'true'}},console:{info(){}},Date,Event,URL,AbortController,TextDecoder,Uint8Array,setTimeout,clearTimeout,...extras});return m.exports;}
function store(storage=new Map(),flag='true'){const window={localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},dispatchEvent(){},matchMedia:()=>({matches:false})};return {api:load('pwa-diagnostics.ts',{window,navigator:{},process:{env:{NEXT_PUBLIC_DEV_PWA_DIAGNOSTICS:flag}}}),storage};}
test('disabled route 404 and diagnostics never write',()=>{const h=store(new Map(),'false');h.api.pwaLog('beforeinstallprompt received');assert.equal(h.storage.size,0);let denied=false;const m=load('../../app/pwa-diagnostics/page.tsx',{process:{env:{}},require:n=>n==='next/navigation'?{notFound(){denied=true;throw Error('404');}}:n==='react/jsx-runtime'?{jsx(){}}:{PwaDiagnosticsPanel(){}}});assert.throws(()=>m.default(),/404/);assert.equal(denied,true);});
test('events persist across reload, accepted/dismissed/appinstalled do not imply real standalone',()=>{const h=store();for(const e of ['beforeinstallprompt received','userChoice=accepted','appinstalled received','userChoice=dismissed'])h.api.pwaLog(e);assert.equal(h.api.actualStandalone(),false);const reload=store(h.storage);assert.equal(reload.api.timeline().length,4);assert.match(reload.api.classification(reload.api.timeline(),true),/recusada/);});
test('clear removes only diagnostic key and bounds timeline',()=>{const h=store();h.storage.set('booking-identity','untouched');for(let i=0;i<260;i++)h.api.pwaLog('focus');assert.equal(h.api.timeline().length,250);h.api.clearDiagnostics();assert.equal(h.storage.get('booking-identity'),'untouched');assert.equal(h.storage.has(h.api.DIAG_KEY),false);assert.equal(h.api.timeline().length,0);});
test('persisted data is revalidated and PII payload is excluded',()=>{const h=store();h.storage.set(h.api.DIAG_KEY,JSON.stringify([{at:Date.now(),event:'userChoice=accepted',details:{email:'secret@example.com',token:'secret-token',errorType:'secret-token',previous:'secret-token'}},{at:Date.now(),event:'secret@example.com',details:{}}]));const report=JSON.stringify(h.api.timeline());assert.doesNotMatch(report,/secret/);assert.equal(h.api.timeline().length,1);assert.equal(h.api.safePath('/agendar/private-slug'),'/agendar/[slug]');});
const r=load('pwa-resource-checks.ts',{require:()=>({enabled:()=>true})});
const bytes=s=>new TextEncoder().encode(s);
test('manifest JSON accepted; HTML rejected for manifest and SW',()=>{const m=r.inspectBytes('/manifest.webmanifest','application/manifest+json',bytes(JSON.stringify({name:'Brand',short_name:'Brand',start_url:'/acesso',scope:'/',display:'standalone',icons:[]})));assert.equal(m.ok,true);for(const p of ['/manifest.webmanifest','/sw.js']){const v=r.inspectBytes(p,'text/html',bytes('<!DOCTYPE html><html>ngrok'));assert.equal(v.ok,false);assert.equal(v.isHtml,true);assert.equal(v.possibleInterstitial,true);}});
test('PNG signature plus MIME required',()=>{const png=new Uint8Array([137,80,78,71,13,10,26,10]);assert.equal(r.inspectBytes('/icons/pwa-icon-192.png','image/png',png).ok,true);assert.equal(r.inspectBytes('/icons/pwa-icon-192.png','text/html',png).ok,false);assert.equal(r.inspectBytes('/icons/pwa-icon-192.png','image/png',bytes('<html>')).ok,false);});
test('resource allowlist rejects tokens, external requests and private routes',()=>{for(const p of ['https://evil.example/icons/a.png','/api/identity','/icons/a.png?token=private','/icons/../api/me','/sw.js#private'])assert.equal(r.publicResource(p,'https://example.com'),null);assert.equal(r.publicResource('/sw.js','https://example.com'),'https://example.com/sw.js');});
test('include and omit are explicit without auth/bypass headers; no redirect forwarding',async()=>{const calls=[];const api=load('pwa-resource-checks.ts',{location:{origin:'https://example.com'},require:()=>({enabled:()=>true}),fetch:async(u,o)=>{calls.push(o);return {type:'opaqueredirect',status:0};}});for(const c of ['include','omit']){const v=await api.checkResource('/sw.js',c);assert.equal(v.ok,false);assert.equal(v.redirected,true);}assert.equal(calls[0].credentials,'include');assert.equal(calls[1].credentials,'omit');assert.equal(calls[0].redirect,'manual');assert.equal(calls[0].headers,undefined);});

