const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const P='esthya:preferred-tenant',K='esthya:known-tenants',I='esthya:booking-identity:';
function setup(values={},options={}) {
  const data=new Map(Object.entries(values));let writes=0,reads=0;
  const storage={getItem(k){reads++;if(options.unreadable)throw Error('secret');return data.get(k)??null;},key(i){if(options.enumerationBlocked)throw Error('secret');return [...data.keys()][i]??null;},get length(){if(options.enumerationBlocked)throw Error('secret');return data.size;},setItem(){writes++;throw Error('mutation');},removeItem(){writes++;throw Error('mutation');},clear(){writes++;throw Error('mutation');}};
  const window={get localStorage(){if(options.blocked)throw Error('secret');return storage;},matchMedia:q=>({matches:q===`(display-mode: ${options.mode||'browser'})`})};
  const module={exports:{}};
  vm.runInNewContext(ts.transpileModule(fs.readFileSync(__dirname+'/recurring-storage-snapshot.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,window,navigator:{standalone:options.standalone},location:{origin:'https://example.com',pathname:'/pwa-diagnostics'},require(n){assert.equal(n,'./pwa-diagnostics');return {enabled:()=>options.enabled!==false,safePath:p=>p==='/pwa-diagnostics'?p:'/[redacted]'};}});
  return {api:module.exports,data,get writes(){return writes;},get reads(){return reads;}};
}
test('absent records are read-only and do not imply a selected identity',()=>{const h=setup();const s=h.api.recurringStorageSnapshot();assert.equal(s.preferredTenantPresent,false);assert.equal(s.preferredTenantValid,false);assert.equal(s.knownTenantsCount,0);assert.equal(s.knownTenantsParseValid,false);assert.equal(s.selectedTenantIdentityPresent,null);assert.equal(s.tenantScopedIdentitiesCount,0);assert.equal(h.writes,0);assert.equal(h.data.size,0);});
test('valid records: report contains indicators only and no mutation',()=>{const h=setup({[P]:JSON.stringify({slug:'secret-tenant',client:'Secret Person'}),[K]:JSON.stringify([{slug:'secret-tenant',displayName:'Secret Business',phone:'5511999999999'}]),[I+'secret-tenant']:'secret-token-hash'});const before=[...h.data];const s=h.api.recurringStorageSnapshot();assert.equal(s.preferredTenantValid,true);assert.equal(s.knownTenantsCount,1);assert.equal(s.selectedTenantIdentityPresent,true);assert.equal(s.tenantScopedIdentitiesCount,1);const report=h.api.recurringStorageReport(s);assert.match(report,/RECURRING ACCESS STORAGE SNAPSHOT/);assert.doesNotMatch(report,/secret|Secret|5511999999999/);assert.deepEqual([...h.data],before);assert.equal(h.writes,0);});
test('corrupt and structurally invalid values remain byte-for-byte intact',()=>{for(const value of ['{broken','null','42','{}','"secret"']){const h=setup({[P]:value,[K]:value});const before=[...h.data];const s=h.api.recurringStorageSnapshot();assert.equal(s.preferredTenantPresent,true);assert.equal(s.preferredTenantValid,false);assert.equal(s.knownTenantsParseValid,false);assert.equal(s.knownTenantsCount,null);assert.deepEqual([...h.data],before);assert.equal(h.writes,0);}});
test('multiple tenants expose unique valid count, never select arbitrarily',()=>{const h=setup({[K]:JSON.stringify([{slug:'private-one'},{slug:'private-two'},{slug:'private-one'},{slug:'!invalid'},null]),[I+'private-one']:'secret',[I+'private-two']:'secret'});const s=h.api.recurringStorageSnapshot();assert.equal(s.knownTenantsCount,2);assert.equal(s.knownTenantsParseValid,true);assert.equal(s.selectedTenantIdentityPresent,null);assert.equal(s.tenantScopedIdentitiesCount,2);assert.doesNotMatch(h.api.recurringStorageReport(s),/private|secret/);assert.equal(h.writes,0);});
test('one known tenant fallback and preferred selection inspect only that identity',()=>{const h=setup({[K]:JSON.stringify([{slug:'tenant-one'}]),[I+'tenant-one']:'secret'});assert.equal(h.api.recurringStorageSnapshot().selectedTenantIdentityPresent,true);h.data.set(P,JSON.stringify({slug:'tenant-two'}));assert.equal(h.api.recurringStorageSnapshot().selectedTenantIdentityPresent,false);});
test('browser and iOS standalone are distinguished',()=>{assert.equal(setup().api.recurringStorageSnapshot().executionContext,'browser');const s=setup({},{standalone:true}).api.recurringStorageSnapshot();assert.equal(s.executionContext,'standalone');assert.equal(s.navigatorStandalone,true);assert.equal(s.displayMode,'standalone');assert.equal(setup({},{mode:'standalone'}).api.recurringStorageSnapshot().executionContext,'standalone');});
test('blocked storage, failed reads and unavailable enumeration do not masquerade as empty',()=>{const blocked=setup({},{blocked:true}).api.recurringStorageSnapshot();assert.equal(blocked.localStorageAvailable,false);assert.equal(blocked.knownTenantsCount,null);const unreadable=setup({},{unreadable:true}).api.recurringStorageSnapshot();assert.equal(unreadable.localStorageAvailable,true);assert.equal(unreadable.localStorageReadable,false);assert.equal(unreadable.preferredTenantPresent,null);const enumeration=setup({},{enumerationBlocked:true}).api.recurringStorageSnapshot();assert.equal(enumeration.localStorageReadable,true);assert.equal(enumeration.tenantScopedIdentitiesCount,null);});
test('DEV disabled: no storage access and no snapshot',()=>{const h=setup({},{enabled:false,blocked:true});assert.equal(h.api.recurringStorageSnapshot(),null);assert.equal(h.reads,0);assert.equal(h.writes,0);});
test('panel includes the same snapshot in visible and copied report',()=>{const source=fs.readFileSync(__dirname+'/PwaDiagnosticsPanel.tsx','utf8');assert.match(source,/recurringStorageReport\(storage\)/);assert.match(source,/block\('RECURRING ACCESS STORAGE SNAPSHOT',storage\)/);assert.match(source,/clipboard.writeText\(report\(\)\)/);});
