const { Router } = require('express');
const authRoutes = require('./auth.routes');
const publicRoutes = require('./public.routes');
const onboardingRoutes = require('./onboarding.routes');
const tenantsRoutes = require('./tenants.routes');
const tenantRoutes = require('./tenant.routes');
const usuariosRoutes = require('./usuarios.routes');
const subscriptionRoutes = require('./subscription.routes');
const agendaRoutes = require('./agenda.routes');
const dashboardRoutes = require('./dashboard.routes');
const settingsRoutes = require('./settings.routes');
const servicesRoutes = require('./services.routes');
const clientsRoutes = require('./clients.routes');
const teamRoutes = require('./team.routes');
const campaignsRoutes = require('./campaigns.routes');
const cargosRoutes = require('./cargos.routes');
const especialidadesRoutes = require('./especialidades.routes');
const profissionaisRoutes = require('./profissionais.routes');
const adminRoutes = require('./admin.routes');
const businessTypesRoutes = require('./business-types.routes');

const router = Router();

router.use('/public', publicRoutes);
router.use('/auth', authRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/tenants', tenantsRoutes);
router.use('/tenant', tenantRoutes);
router.use('/usuarios', usuariosRoutes);
router.use('/subscription', subscriptionRoutes);
router.use('/agenda', agendaRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/settings', settingsRoutes);
router.use('/services', servicesRoutes);
router.use('/clients', clientsRoutes);
router.use('/team', teamRoutes);
router.use('/campaigns', campaignsRoutes);
router.use('/cargos', cargosRoutes);
router.use('/especialidades', especialidadesRoutes);
router.use('/profissionais', profissionaisRoutes);
router.use('/admin', adminRoutes);
router.use('/tipos-negocio', businessTypesRoutes);

module.exports = router;
